version: "3"
   
services:
    django:
        build: .
        container_name: django
        command: ./start-django.sh
        volumes:
            - .:/usr/src/app/
            - tmp:/tmp
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
    celery:
        build: .
        container_name: celery
        command: celery -A configurations worker -l DEBUG
        volumes:
            - .:/usr/src/app
            - tmp:/tmp
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    redis:
        image: "redis:alpine"

volumes:
    tmp:
        

