version: "3.3"
   
services:
    django:
        build: .
        container_name: django
        command: ./start-django.sh
        volumes:
            - .:/usr/src/app/
            - tmp:/tmp
        ports:
            - "8000:8000"
        env_file: 
            - .env-example
        depends_on:
            - redis
    celery:
        build: .
        container_name: celery
        command: celery -A configurations worker -l DEBUG
        volumes:
            - .:/usr/src/app
            - tmp:/tmp
        env_file:
            - .env-example
        depends_on:
            - django
            - redis
    redis:
        image: "redis:alpine"

volumes:
    tmp:
        

